kernel: bpf_trace: Remove inline that causes gcc error
../kernel/trace/bpf_trace.c: In function 'bpf_do_trace_printk':
../kernel/trace/bpf_trace.c:167:34: error: function 'bpf_do_trace_printk' can never be inlined because it uses variable argument lists
  167 | static inline __printf(1, 0) int bpf_do_trace_printk(const char *fmt, ...)
      |                                  ^~~~~~~~~~~~~~~~~~~

Signed-off-by: farizmaul <nickshade88@gmail.com>